### ISSUE TITLE
Test failure with minitest 5.16

### ISSUE THREAD

**Issue by felixonmars** [grosser/maxitest#38]
```
rspec spec/
......................F..............

Failures:

  1) Maxitest extra threads fails on extra and passes on regular
     Failure/Error:
       result.gsub(/\d\.\d+/, "0.0").should include <<-OUT.gsub(/^\s+/, "")
         threads#test_0001_is fine without extra threads = 0.0 s = .
         threads#test_0002_fails on extra threads = 0.0 s = F
         threads#test_0003_can kill extra threads = 0.0 s = .
         threads#test_0004_can wait for extra threads = 0.0 s = .
       OUT

       expected "Run options: -v --seed 31005\n\n# Running:\n\nthreads#test_0001_is fine without extra threads = 0.0 ...5\nmtest spec/cases/threads.rb:19\nmtest spec/cases/threads.rb:25\nmtest spec/cases/threads.rb:31\n" to include "threads#test_0001_is fine without extra threads = 0.0 s = .\nthreads#test_0002_fails on extra thread...0003_can kill extra threads = 0.0 s = .\nthreads#test_0004_can wait for extra threads = 0.0 s = .\n"
       Diff:
       @@ -1,158 +1,315 @@
       -threads#test_0001_is fine without extra threads = 0.0 s = .\nthreads#test_0002_fails on extra threads = 0.0 s = F\nthreads#test_0003_can kill extra threads = 0.0 s = .\nthreads#test_0004_can wait for extra threads = 0.0 s = .\n
       +Run options: -v --seed 31005
       +
       +# Running:
       +
       +threads#test_0001_is fine without extra threads = 0.0 s = F
       +threads#test_0002_fails on extra threads = 0.0 s = F
       +threads#test_0003_can kill extra threads = 0.0 s = F
       +threads#test_0004_can wait for extra threads = 0.0 s = F
       +
       +Finished in 0.0s, 500.0 runs/s, 500.0 assertions/s.
       +
       +  1) Failure:
       +threads#test_0001_is fine without extra threads [spec/cases/threads.rb:16]:
       +Minitest::Assertion: Expected: 3
       +  Actual: 33
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/assertions.rb:183:in `assert'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/assertions.rb:218:in `assert_equal'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/spec.rb:28:in `must_equal'
       +    /build/ruby-maxitest/src/maxitest-0.0.0/lib/maxitest/global_must.rb:14:in `must_equal'
       +    spec/cases/threads.rb:8:in `assert_correct_threads'
       +    spec/cases/threads.rb:16:in `block (2 levels) in <main>'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/test.rb:98:in `block (3 levels) in run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/test.rb:195:in `capture_exceptions'
       +    /build/ruby-maxitest/src/maxitest-0.0.0/lib/maxitest/trap.rb:4:in `capture_exceptions'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/test.rb:95:in `block (2 levels) in run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:296:in `time_it'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/test.rb:94:in `block in run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:391:in `on_signal'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/test.rb:243:in `with_info_handler'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/test.rb:93:in `run'
       +    /build/ruby-maxitest/src/maxitest-0.0.0/lib/maxitest/vendor/around.rb:47:in `run'
       +    /build/ruby-maxitest/src/maxitest-0.0.0/lib/maxitest/trap.rb:23:in `run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:1059:in `run_one_method'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:365:in `run_one_method'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:352:in `block (2 levels) in run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:351:in `each'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:351:in `block in run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:391:in `on_signal'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:378:in `with_info_handler'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:350:in `run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:182:in `block in __run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:182:in `map'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:182:in `__run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:159:in `run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:83:in `block in autorun'
       +
       +  2) Failure:
       +threads#test_0002_fails on extra threads [spec/cases/threads.rb:20]:
       +Minitest::Assertion: Expected: 3
       +  Actual: 33
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/assertions.rb:183:in `assert'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/assertions.rb:218:in `assert_equal'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/spec.rb:28:in `must_equal'
       +    /build/ruby-maxitest/src/maxitest-0.0.0/lib/maxitest/global_must.rb:14:in `must_equal'
       +    spec/cases/threads.rb:8:in `assert_correct_threads'
       +    spec/cases/threads.rb:20:in `block (2 levels) in <main>'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/test.rb:98:in `block (3 levels) in run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/test.rb:195:in `capture_exceptions'
       +    /build/ruby-maxitest/src/maxitest-0.0.0/lib/maxitest/trap.rb:4:in `capture_exceptions'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/test.rb:95:in `block (2 levels) in run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:296:in `time_it'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/test.rb:94:in `block in run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:391:in `on_signal'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/test.rb:243:in `with_info_handler'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/test.rb:93:in `run'
       +    /build/ruby-maxitest/src/maxitest-0.0.0/lib/maxitest/vendor/around.rb:47:in `run'
       +    /build/ruby-maxitest/src/maxitest-0.0.0/lib/maxitest/trap.rb:23:in `run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:1059:in `run_one_method'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:365:in `run_one_method'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:352:in `block (2 levels) in run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:351:in `each'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:351:in `block in run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:391:in `on_signal'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:378:in `with_info_handler'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:350:in `run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:182:in `block in __run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:182:in `map'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:182:in `__run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:159:in `run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:83:in `block in autorun'
       +
       +  3) Failure:
       +threads#test_0003_can kill extra threads [spec/cases/threads.rb:26]:
       +Minitest::Assertion: Expected: 3
       +  Actual: 33
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/assertions.rb:183:in `assert'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/assertions.rb:218:in `assert_equal'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/spec.rb:28:in `must_equal'
       +    /build/ruby-maxitest/src/maxitest-0.0.0/lib/maxitest/global_must.rb:14:in `must_equal'
       +    spec/cases/threads.rb:8:in `assert_correct_threads'
       +    spec/cases/threads.rb:26:in `block (2 levels) in <main>'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/test.rb:98:in `block (3 levels) in run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/test.rb:195:in `capture_exceptions'
       +    /build/ruby-maxitest/src/maxitest-0.0.0/lib/maxitest/trap.rb:4:in `capture_exceptions'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/test.rb:95:in `block (2 levels) in run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:296:in `time_it'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/test.rb:94:in `block in run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:391:in `on_signal'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/test.rb:243:in `with_info_handler'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/test.rb:93:in `run'
       +    /build/ruby-maxitest/src/maxitest-0.0.0/lib/maxitest/vendor/around.rb:47:in `run'
       +    /build/ruby-maxitest/src/maxitest-0.0.0/lib/maxitest/trap.rb:23:in `run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:1059:in `run_one_method'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:365:in `run_one_method'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:352:in `block (2 levels) in run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:351:in `each'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:351:in `block in run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:391:in `on_signal'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:378:in `with_info_handler'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:350:in `run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:182:in `block in __run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:182:in `map'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:182:in `__run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:159:in `run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:83:in `block in autorun'
       +
       +  4) Failure:
       +threads#test_0004_can wait for extra threads [spec/cases/threads.rb:32]:
       +Minitest::Assertion: Expected: 3
       +  Actual: 33
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/assertions.rb:183:in `assert'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/assertions.rb:218:in `assert_equal'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/spec.rb:28:in `must_equal'
       +    /build/ruby-maxitest/src/maxitest-0.0.0/lib/maxitest/global_must.rb:14:in `must_equal'
       +    spec/cases/threads.rb:8:in `assert_correct_threads'
       +    spec/cases/threads.rb:32:in `block (2 levels) in <main>'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/test.rb:98:in `block (3 levels) in run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/test.rb:195:in `capture_exceptions'
       +    /build/ruby-maxitest/src/maxitest-0.0.0/lib/maxitest/trap.rb:4:in `capture_exceptions'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/test.rb:95:in `block (2 levels) in run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:296:in `time_it'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/test.rb:94:in `block in run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:391:in `on_signal'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/test.rb:243:in `with_info_handler'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest/test.rb:93:in `run'
       +    /build/ruby-maxitest/src/maxitest-0.0.0/lib/maxitest/vendor/around.rb:47:in `run'
       +    /build/ruby-maxitest/src/maxitest-0.0.0/lib/maxitest/trap.rb:23:in `run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:1059:in `run_one_method'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:365:in `run_one_method'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:352:in `block (2 levels) in run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:351:in `each'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:351:in `block in run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:391:in `on_signal'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:378:in `with_info_handler'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:350:in `run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:182:in `block in __run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:182:in `map'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:182:in `__run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:159:in `run'
       +    /usr/lib/ruby/gems/0.0.0/gems/minitest-0.0.3/lib/minitest.rb:83:in `block in autorun'
       +
       +4 runs, 4 assertions, 4 failures, 0 errors, 0 skips
       +
       +Focus on failing tests:
       +mtest spec/cases/threads.rb:15
       +mtest spec/cases/threads.rb:19
       +mtest spec/cases/threads.rb:25
       +mtest spec/cases/threads.rb:31
     # ./spec/maxitest_spec.rb:159:in `block (3 levels) in <top (required)>'

Finished in 8.43 seconds (files took 0.05067 seconds to load)
37 examples, 1 failure

Failed examples:

rspec ./spec/maxitest_spec.rb:155 # Maxitest extra threads fails on extra and passes on regular
```

**Comment by grosser** [comment]
4.2.0
